/* Auto-generated by genmsg_cpp for file /home/ubuntu/AMSL_ros_pkg/rwrc13_msgs/srv/GetGoalsId.srv */
#ifndef RWRC13_MSGS_SERVICE_GETGOALSID_H
#define RWRC13_MSGS_SERVICE_GETGOALSID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "geometry_msgs/PoseStamped.h"

namespace rwrc13_msgs
{
template <class ContainerAllocator>
struct GetGoalsIdRequest_ {
  typedef GetGoalsIdRequest_<ContainerAllocator> Type;

  GetGoalsIdRequest_()
  {
  }

  GetGoalsIdRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetGoalsIdRequest
typedef  ::rwrc13_msgs::GetGoalsIdRequest_<std::allocator<void> > GetGoalsIdRequest;

typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdRequest> GetGoalsIdRequestPtr;
typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdRequest const> GetGoalsIdRequestConstPtr;



template <class ContainerAllocator>
struct GetGoalsIdResponse_ {
  typedef GetGoalsIdResponse_<ContainerAllocator> Type;

  GetGoalsIdResponse_()
  : goals()
  , id(0)
  , turn(false)
  {
  }

  GetGoalsIdResponse_(const ContainerAllocator& _alloc)
  : goals(_alloc)
  , id(0)
  , turn(false)
  {
  }

  typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _goals_type;
  std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  goals;

  typedef int32_t _id_type;
  int32_t id;

  typedef uint8_t _turn_type;
  uint8_t turn;


  typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetGoalsIdResponse
typedef  ::rwrc13_msgs::GetGoalsIdResponse_<std::allocator<void> > GetGoalsIdResponse;

typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdResponse> GetGoalsIdResponsePtr;
typedef boost::shared_ptr< ::rwrc13_msgs::GetGoalsIdResponse const> GetGoalsIdResponseConstPtr;


struct GetGoalsId
{

typedef GetGoalsIdRequest Request;
typedef GetGoalsIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetGoalsId
} // namespace rwrc13_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rwrc13_msgs/GetGoalsIdRequest";
  }

  static const char* value(const  ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c21fa0e1ad0759ded1a6c5f000b3508c";
  }

  static const char* value(const  ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc21fa0e1ad0759deULL;
  static const uint64_t static_value2 = 0xd1a6c5f000b3508cULL;
};

template<class ContainerAllocator>
struct DataType< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rwrc13_msgs/GetGoalsIdResponse";
  }

  static const char* value(const  ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PoseStamped[] goals\n\
int32 id\n\
bool turn\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetGoalsIdRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.goals);
    stream.next(m.id);
    stream.next(m.turn);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetGoalsIdResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<rwrc13_msgs::GetGoalsId> {
  static const char* value() 
  {
    return "c21fa0e1ad0759ded1a6c5f000b3508c";
  }

  static const char* value(const rwrc13_msgs::GetGoalsId&) { return value(); } 
};

template<>
struct DataType<rwrc13_msgs::GetGoalsId> {
  static const char* value() 
  {
    return "rwrc13_msgs/GetGoalsId";
  }

  static const char* value(const rwrc13_msgs::GetGoalsId&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c21fa0e1ad0759ded1a6c5f000b3508c";
  }

  static const char* value(const rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rwrc13_msgs/GetGoalsId";
  }

  static const char* value(const rwrc13_msgs::GetGoalsIdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c21fa0e1ad0759ded1a6c5f000b3508c";
  }

  static const char* value(const rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rwrc13_msgs/GetGoalsId";
  }

  static const char* value(const rwrc13_msgs::GetGoalsIdResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RWRC13_MSGS_SERVICE_GETGOALSID_H

