(cl:in-package rwrc13_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          PRECISION-VAL
          PRECISION
          SATELITES-VAL
          SATELITES
          HDOP-VAL
          HDOP
          ALT-VAL
          ALT
          GEO-VAL
          GEO
          LACK-VAL
          LACK
          RMS-VAL
          RMS
          SMD1-VAL
          SMD1
          SMD2-VAL
          SMD2
          SMO-VAL
          SMO
          LAED-VAL
          LAED
          LOED-VAL
          LOED
          ALED-VAL
          ALED
          PDOP-VAL
          PDOP
          VDOP-VAL
          VDOP
          GS-VAL
          GS
))