(cl:in-package rwrc13_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          PRECISION-VAL
          PRECISION
          SATELITES-VAL
          SATELITES
          HDOP-VAL
          HDOP
          ALT-VAL
          ALT
          GEO-VAL
          GEO
          LACK-VAL
          LACK
          RMS-VAL
          RMS
          SMD1-VAL
          SMD1
          SMD2-VAL
          SMD2
          SMO-VAL
          SMO
          LAED-VAL
          LAED
          LOED-VAL
          LOED
          ALED-VAL
          ALED
          ID-VAL
          ID
          PDOP-VAL
          PDOP
          VDOP-VAL
          VDOP
          GS-VAL
          GS
          TN-VAL
          TN
          MN-VAL
          MN
          SN-VAL
          SN
          ELEVATION-VAL
          ELEVATION
          AZIMUTH-VAL
          AZIMUTH
          SNR-VAL
          SNR
          SA1-VAL
          SA1
          SA2-VAL
          SA2
          SA3-VAL
          SA3
          SA4-VAL
          SA4
          SA5-VAL
          SA5
          SA6-VAL
          SA6
          SA7-VAL
          SA7
          SA8-VAL
          SA8
))