/* Auto-generated by genmsg_cpp for file /home/amsl/AMSL_ros_pkg/rwrc13_msgs/msg/MultiDataCell.msg */
#ifndef RWRC13_MSGS_MESSAGE_MULTIDATACELL_H
#define RWRC13_MSGS_MESSAGE_MULTIDATACELL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "rwrc13_msgs/CellBase.h"

namespace rwrc13_msgs
{
template <class ContainerAllocator>
struct MultiDataCell_ {
  typedef MultiDataCell_<ContainerAllocator> Type;

  MultiDataCell_()
  : base()
  , mean_height(0.0)
  , mean_intensity(0.0)
  {
  }

  MultiDataCell_(const ContainerAllocator& _alloc)
  : base(_alloc)
  , mean_height(0.0)
  , mean_intensity(0.0)
  {
  }

  typedef  ::rwrc13_msgs::CellBase_<ContainerAllocator>  _base_type;
   ::rwrc13_msgs::CellBase_<ContainerAllocator>  base;

  typedef float _mean_height_type;
  float mean_height;

  typedef float _mean_intensity_type;
  float mean_intensity;


  typedef boost::shared_ptr< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator>  const> ConstPtr;
}; // struct MultiDataCell
typedef  ::rwrc13_msgs::MultiDataCell_<std::allocator<void> > MultiDataCell;

typedef boost::shared_ptr< ::rwrc13_msgs::MultiDataCell> MultiDataCellPtr;
typedef boost::shared_ptr< ::rwrc13_msgs::MultiDataCell const> MultiDataCellConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rwrc13_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> > {
  static const char* value() 
  {
    return "871d66fdcb3b83d9ad36d9b8b98aeaa7";
  }

  static const char* value(const  ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x871d66fdcb3b83d9ULL;
  static const uint64_t static_value2 = 0xad36d9b8b98aeaa7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rwrc13_msgs/MultiDataCell";
  }

  static const char* value(const  ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CellBase base\n\
#geometry_msgs/Point32[] points\n\
float32 mean_height\n\
float32 mean_intensity\n\
\n\
================================================================================\n\
MSG: rwrc13_msgs/CellBase\n\
Header header\n\
float32 cell_width\n\
float32 cell_height\n\
geometry_msgs/Point32 position\n\
geometry_msgs/Point32[] points\n\
float32[] intensity\n\
int8 cost\n\
string label\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const  ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.base);
    stream.next(m.mean_height);
    stream.next(m.mean_intensity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MultiDataCell_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rwrc13_msgs::MultiDataCell_<ContainerAllocator> & v) 
  {
    s << indent << "base: ";
s << std::endl;
    Printer< ::rwrc13_msgs::CellBase_<ContainerAllocator> >::stream(s, indent + "  ", v.base);
    s << indent << "mean_height: ";
    Printer<float>::stream(s, indent + "  ", v.mean_height);
    s << indent << "mean_intensity: ";
    Printer<float>::stream(s, indent + "  ", v.mean_intensity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RWRC13_MSGS_MESSAGE_MULTIDATACELL_H

