(cl:defpackage rwrc13_msgs-srv
  (:use )
  (:export
   "GETGOALS"
   "<GETGOALS-REQUEST>"
   "GETGOALS-REQUEST"
   "<GETGOALS-RESPONSE>"
   "GETGOALS-RESPONSE"
   "GETGOALSID"
   "<GETGOALSID-REQUEST>"
   "GETGOALSID-REQUEST"
   "<GETGOALSID-RESPONSE>"
   "GETGOALSID-RESPONSE"
   "PATHCHECK"
   "<PATHCHECK-REQUEST>"
   "PATHCHECK-REQUEST"
   "<PATHCHECK-RESPONSE>"
   "PATHCHECK-RESPONSE"
  ))

